Add travis yml config file to coordinate automatic deploy to gh-pages branch from master. Fixes #42
cds-hooks/legacy-sandbox pull request #43
Opened 2017-07-06 20:09 UTC by zplata

Currently, to add changes to the CDS Hooks Sandbox tool, developers have to add an extra PR to the `gh-pages` branch in addition to their PR to `master`. This allows their change to reflect in the host site but adds an extra complex step. We should explore using Travis CI to do auto-deployments to the `gh-pages` branch from `master` so that once changes are merged into master, Travis CI will deploy the change to the hosted site automatically. Everything in the `/build` folder will be deployed on the `gh-pages` branch.

We also have to [configure this repository](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI) to allow Travis CI to run on it.

2017-07-13 02:06 UTC, kpshek approved these changes
Thanks @zplata

2017-07-13 02:07 UTC, kpshek requested changes
@zplata - Can you update this PR to resolve the conflicts?

2017-07-13 17:18 UTC, zplata commented
@kpshek Conflicts resolved

2017-07-14 13:26 UTC, kpshek approved these changes

2017-07-14 13:27 UTC, merged